# docker-compose.yml pour Nailloux-club : Conteneurisation avec Nginx Reverse Proxy
# Définit les services 'nginx' (reverse proxy), 'app' (PHP/Apache) et 'db' (MySQL 8.0)
# Configure les volumes, réseaux et variables d'environnement
# Déploiement sur machine 10.0.1.3
services:
  nginx:
    image: nginx:alpine
    container_name: nailloux-club-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - nailloux-network
    depends_on:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nailloux-club-app
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - DB_HOST=db
      - DB_NAME=nailloux
      - DB_USER=root
      - DB_PASSWORD=rootpassword
    volumes:
      - ./:/var/www/html
      - ./upload:/var/www/html/upload
    networks:
      - nailloux-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: nailloux-club-db
    restart: unless-stopped
    ports:
      - "33060:3306" # Changed port to avoid conflicts
    environment:
      MYSQL_DATABASE: nailloux
      MYSQL_ROOT_PASSWORD: rootpassword
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    volumes:
      - dbdata:/var/lib/mysql
      - ./nailloux.sql:/docker-entrypoint-initdb.d/nailloux.sql
    networks:
      - nailloux-network

networks:
  nailloux-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
